export const CENTROIDS: Record<string, [number, number]> = {
  // Western & Northern Europe
  "Norway":              [64.5, 17.5],
  "Sweden":              [62.0, 16.5],
  "Finland":             [64.5, 26.0],
  "Denmark":             [56.0,  9.5],
  "United Kingdom":      [54.0, -2.5],
  "Ireland":             [53.2, -8.0],
  // Baltic States
  "Estonia":             [58.7, 25.0],
  "Latvia":              [56.8, 24.6],
  "Lithuania":           [55.8, 24.0],
  // Central Western Europe
  "Germany":             [51.2, 10.5],
  "Netherlands":         [52.2,  5.3],
  "Belgium":             [50.5,  4.5],
  "Luxembourg":          [49.8,  6.1],
  "France":              [46.5,  2.5],
  "Switzerland":         [46.8,  8.2],
  "Austria":             [47.5, 14.5],
  // Iberian Peninsula
  "Spain":               [40.4, -3.5],
  "Portugal":            [39.5, -8.0],
  // Central Eastern Europe
  "Poland":              [52.0, 20.0],
  "Czech Republic":      [49.8, 15.5],
  "Slovakia":            [48.7, 19.5],
  "Hungary":             [47.2, 19.0],
  // Southern Europe
  "Italy":               [42.5, 13.0],
  "Slovenia":            [46.1, 14.8],
  "Croatia":             [45.2, 16.0],
  "Greece":              [39.5, 22.0],
  // South-Eastern Europe / Balkans
  "Romania":             [45.8, 24.7],
  "Bulgaria":            [42.7, 25.5],
  "Serbia":              [44.0, 21.0],
  "Bosnia":              [44.2, 17.5],
  "Montenegro":          [42.7, 19.4],
  "North Macedonia":     [41.6, 21.7],
  "Albania":             [41.2, 20.2],
  "Moldova":             [47.4, 28.4],
  "Turkey":              [39.0, 33.5],
};

export const INTERCONNECTORS: Array<{ from: string; to: string; capacityMw: number; label: string }> = [
  // Nordic
  { from: "Norway",          to: "Sweden",          capacityMw: 3500, label: "NO–SE" },
  { from: "Norway",          to: "Finland",         capacityMw: 700,  label: "NO–FI" },
  { from: "Norway",          to: "Denmark",         capacityMw: 1700, label: "NO–DK" },
  { from: "Norway",          to: "Netherlands",     capacityMw: 700,  label: "NorNed (NO–NL)" },
  { from: "Norway",          to: "United Kingdom",  capacityMw: 1400, label: "North Sea Link (NO–GB)" },
  { from: "Norway",          to: "Germany",         capacityMw: 1400, label: "NordLink (NO–DE)" },
  { from: "Sweden",          to: "Finland",         capacityMw: 3200, label: "SE–FI" },
  { from: "Sweden",          to: "Denmark",         capacityMw: 2100, label: "SE–DK" },
  { from: "Sweden",          to: "Poland",          capacityMw: 600,  label: "SwePol (SE–PL)" },
  { from: "Denmark",         to: "Germany",         capacityMw: 2500, label: "DK–DE" },
  { from: "Denmark",         to: "Netherlands",     capacityMw: 700,  label: "COBRAcable (DK–NL)" },
  // Baltic States
  { from: "Estonia",         to: "Latvia",          capacityMw: 2200, label: "EE–LV" },
  { from: "Estonia",         to: "Finland",         capacityMw: 1000, label: "Estlink (EE–FI)" },
  { from: "Latvia",          to: "Lithuania",       capacityMw: 2200, label: "LV–LT" },
  { from: "Lithuania",       to: "Poland",          capacityMw: 500,  label: "LitPol (LT–PL)" },
  // Central Western Europe
  { from: "Germany",         to: "Netherlands",     capacityMw: 5900, label: "DE–NL" },
  { from: "Germany",         to: "Belgium",         capacityMw: 3600, label: "DE–BE" },
  { from: "Germany",         to: "France",          capacityMw: 4000, label: "DE–FR" },
  { from: "Germany",         to: "Poland",          capacityMw: 3200, label: "DE–PL" },
  { from: "Germany",         to: "Switzerland",     capacityMw: 4200, label: "DE–CH" },
  { from: "Germany",         to: "Austria",         capacityMw: 5000, label: "DE–AT" },
  { from: "Germany",         to: "Czech Republic",  capacityMw: 2000, label: "DE–CZ" },
  { from: "Germany",         to: "Luxembourg",      capacityMw: 800,  label: "DE–LU" },
  { from: "France",          to: "Belgium",         capacityMw: 3200, label: "FR–BE" },
  { from: "France",          to: "Spain",           capacityMw: 2800, label: "FR–ES" },
  { from: "France",          to: "Italy",           capacityMw: 3600, label: "FR–IT" },
  { from: "France",          to: "Switzerland",     capacityMw: 3600, label: "FR–CH" },
  { from: "France",          to: "United Kingdom",  capacityMw: 2000, label: "IFA (FR–GB)" },
  { from: "France",          to: "Luxembourg",      capacityMw: 1600, label: "FR–LU" },
  { from: "Belgium",         to: "Netherlands",     capacityMw: 3500, label: "BE–NL" },
  { from: "Belgium",         to: "United Kingdom",  capacityMw: 1000, label: "Nemo Link (BE–GB)" },
  { from: "Belgium",         to: "Luxembourg",      capacityMw: 400,  label: "BE–LU" },
  { from: "United Kingdom",  to: "Ireland",         capacityMw: 750,  label: "Moyle + East-West (GB–IE)" },
  // Switzerland / Austria
  { from: "Switzerland",     to: "Austria",         capacityMw: 2000, label: "CH–AT" },
  { from: "Switzerland",     to: "Italy",           capacityMw: 3500, label: "CH–IT" },
  { from: "Austria",         to: "Italy",           capacityMw: 250,  label: "AT–IT (Brenner)" },
  { from: "Austria",         to: "Czech Republic",  capacityMw: 1100, label: "AT–CZ" },
  { from: "Austria",         to: "Slovakia",        capacityMw: 2100, label: "AT–SK" },
  { from: "Austria",         to: "Hungary",         capacityMw: 1200, label: "AT–HU" },
  { from: "Austria",         to: "Slovenia",        capacityMw: 1850, label: "AT–SI" },
  // Central Eastern Europe
  { from: "Czech Republic",  to: "Slovakia",        capacityMw: 1500, label: "CZ–SK" },
  { from: "Czech Republic",  to: "Poland",          capacityMw: 2000, label: "CZ–PL" },
  { from: "Slovakia",        to: "Hungary",         capacityMw: 1800, label: "SK–HU" },
  { from: "Slovakia",        to: "Poland",          capacityMw: 800,  label: "SK–PL" },
  // South-Eastern Europe
  { from: "Hungary",         to: "Romania",         capacityMw: 1200, label: "HU–RO" },
  { from: "Hungary",         to: "Croatia",         capacityMw: 1000, label: "HU–HR" },
  { from: "Hungary",         to: "Serbia",          capacityMw: 1000, label: "HU–RS" },
  { from: "Hungary",         to: "Slovenia",        capacityMw: 350,  label: "HU–SI" },
  { from: "Romania",         to: "Bulgaria",        capacityMw: 2600, label: "RO–BG" },
  { from: "Romania",         to: "Serbia",          capacityMw: 600,  label: "RO–RS" },
  { from: "Romania",         to: "Moldova",         capacityMw: 600,  label: "RO–MD" },
  { from: "Bulgaria",        to: "Greece",          capacityMw: 1500, label: "BG–GR" },
  { from: "Bulgaria",        to: "Serbia",          capacityMw: 400,  label: "BG–RS" },
  { from: "Bulgaria",        to: "North Macedonia", capacityMw: 400,  label: "BG–MK" },
  { from: "Croatia",         to: "Slovenia",        capacityMw: 2000, label: "HR–SI" },
  { from: "Croatia",         to: "Serbia",          capacityMw: 400,  label: "HR–RS" },
  { from: "Croatia",         to: "Bosnia",          capacityMw: 600,  label: "HR–BA" },
  { from: "Slovenia",        to: "Italy",           capacityMw: 1000, label: "SI–IT" },
  // Balkans
  { from: "Serbia",          to: "Bosnia",          capacityMw: 1000, label: "RS–BA" },
  { from: "Serbia",          to: "Montenegro",      capacityMw: 1000, label: "RS–ME" },
  { from: "Serbia",          to: "North Macedonia", capacityMw: 400,  label: "RS–MK" },
  { from: "Bosnia",          to: "Montenegro",      capacityMw: 600,  label: "BA–ME" },
  { from: "Montenegro",      to: "Albania",         capacityMw: 400,  label: "ME–AL" },
  { from: "North Macedonia", to: "Greece",          capacityMw: 500,  label: "MK–GR" },
  { from: "North Macedonia", to: "Albania",         capacityMw: 400,  label: "MK–AL" },
  { from: "Albania",         to: "Greece",          capacityMw: 500,  label: "AL–GR" },
  { from: "Albania",         to: "Italy",           capacityMw: 500,  label: "HVDC Ital-Alb" },
  // Turkey borders
  { from: "Turkey",          to: "Greece",          capacityMw: 300,  label: "TR–GR" },
  { from: "Turkey",          to: "Bulgaria",        capacityMw: 1000, label: "TR–BG" },
  // Iberian
  { from: "Spain",           to: "Portugal",        capacityMw: 4200, label: "ES–PT (MIBEL)" },
];
