/**
 * Elia (Belgium TSO) — Generation by Fuel Type
 * https://opendata.elia.be/api/explore/v2.1/
 * Free public API, no auth required. 15-minute resolution from 2019-12-31.
 *
 * Primary datasets:
 *   ods177 — Power generated by contracted technical units, aggregated by fuel type (2024-05-22+)
 *   ods201 — Total generation aggregated by fuel type (2019-12-31+)
 *   ods086 — Wind production estimation (near real-time, with monitored capacity by region)
 *   ods087 — Solar PV production estimation (near real-time, with monitored capacity by region)
 *   ods003 — Load on the Elia grid (current, 15-min)
 */

const BASE = "https://opendata.elia.be/api/explore/v2.1/catalog/datasets";

// 30-min cache for live data; 6-hour cache for monthly history
const LIVE_TTL = 30 * 60 * 1000;
const HIST_TTL = 6 * 60 * 60 * 1000;
interface CacheEntry { data: any; ts: number }
const cache: Map<string, CacheEntry> = new Map();

function fromCache(key: string, ttl: number): any | null {
  const e = cache.get(key);
  if (!e || Date.now() - e.ts > ttl) { cache.delete(key); return null; }
  return e.data;
}
function toCache(key: string, data: any) { cache.set(key, { data, ts: Date.now() }); }

// ─── Fuel colour / grouping ──────────────────────────────────────────────────
export const FUEL_MAP: Record<string, string> = {
  "Nuclear":           "Nuclear",
  "Natural Gas":       "Natural Gas",
  "Wind Offshore":     "Wind Offshore",
  "Wind Onshore":      "Wind Onshore",
  "Solar":             "Solar",
  "Biofuels":          "Biofuels",
  "Water":             "Hydro",
  "Energy Storage":    "Storage",
  "Other":             "Other",
  "Other Fossil Fuels":"Other Fossil",
  "Other Fuel":        "Other Fossil",
};

const RENEWABLE_FUELS = new Set(["Wind Offshore", "Wind Onshore", "Solar", "Biofuels", "Hydro"]);
const LOW_CARBON_FUELS = new Set(["Wind Offshore", "Wind Onshore", "Solar", "Biofuels", "Hydro", "Nuclear"]);

// ─── Fetch 12-month history in ONE API call using GROUP BY aggregation ────────
// Elia ODS v2.1 supports avg(generatedpower) with group_by on year/month
async function fetchAllMonthlyHistory(fromDate: string): Promise<Map<string, Record<string, number>>> {
  // Returns a map: "YYYY-MM" → { FuelType → avgMW }
  // ODS v2.1 quirk: adding aliases causes year(datetime)/month(datetime) to populate in results
  const select = encodeURIComponent(
    "year(datetime) as yr, month(datetime) as mth, fueltypepublication, avg(generatedpower) as avgMW"
  );
  const groupBy = encodeURIComponent("year(datetime), month(datetime), fueltypepublication");
  const where = encodeURIComponent(`datetime >= '${fromDate}'`);

  const url =
    `${BASE}/ods177/records` +
    `?select=${select}&group_by=${groupBy}&where=${where}` +
    `&limit=200&order_by=year(datetime),month(datetime)&timezone=UTC`;

  const resp = await fetch(url, {
    headers: { Accept: "application/json" },
    signal: AbortSignal.timeout(30_000),
  });
  if (!resp.ok) throw new Error(`Elia group-by ${resp.status}`);
  const json = await resp.json();

  const result = new Map<string, Record<string, number>>();
  for (const r of json.results ?? []) {
    const yr: number = r["year(datetime)"] ?? 0;
    const mo: number = r["month(datetime)"] ?? 0;
    if (!yr || !mo) continue;
    const label = `${yr}-${String(mo).padStart(2, "0")}`;
    const raw: string = r.fueltypepublication ?? "";
    const fuel = FUEL_MAP[raw] ?? raw;
    const avgMW: number = r.avgMW ?? 0;
    if (!result.has(label)) result.set(label, {});
    result.get(label)![fuel] = Math.round(avgMW);
  }
  return result;
}

// ─── Live snapshot (most recent 15-min interval) ─────────────────────────────
async function fetchLiveSnapshot(): Promise<{
  timestamp: string;
  byFuel: Record<string, number>;
  totalMW: number;
  renewableSharePct: number;
  lowCarbonSharePct: number;
  gridLoad: number | null;
}> {
  const [genResp, loadResp] = await Promise.all([
    fetch(
      `${BASE}/ods177/records?limit=20&order_by=datetime%20desc&timezone=UTC`,
      { headers: { Accept: "application/json" }, signal: AbortSignal.timeout(12_000) }
    ),
    fetch(
      `${BASE}/ods003/records?limit=1&order_by=datetime%20desc&timezone=UTC`,
      { headers: { Accept: "application/json" }, signal: AbortSignal.timeout(10_000) }
    ).catch(() => null),
  ]);

  if (!genResp.ok) throw new Error(`Elia live gen ${genResp.status}`);
  const genJson = await genResp.json();

  // Get the most recent timestamp
  const latestRecord = genJson.results?.[0];
  const timestamp: string = latestRecord?.datetime ?? new Date().toISOString();
  const totalMW: number = latestRecord?.totalgeneratedpower ?? 0;

  const byFuel: Record<string, number> = {};
  for (const r of genJson.results ?? []) {
    const raw: string = r.fueltypepublication ?? "";
    const fuel = FUEL_MAP[raw] ?? raw;
    const mw: number = r.generatedpower ?? 0;
    byFuel[fuel] = Math.round(mw);
  }

  const totalActual = Object.values(byFuel).reduce((s, v) => s + v, 0);
  const renewableMW = Object.entries(byFuel)
    .filter(([f]) => RENEWABLE_FUELS.has(f))
    .reduce((s, [, v]) => s + v, 0);
  const lowCarbonMW = Object.entries(byFuel)
    .filter(([f]) => LOW_CARBON_FUELS.has(f))
    .reduce((s, [, v]) => s + v, 0);

  let gridLoad: number | null = null;
  if (loadResp?.ok) {
    const loadJson = await loadResp.json();
    gridLoad = loadJson.results?.[0]?.eliagridload ?? null;
  }

  return {
    timestamp,
    byFuel,
    totalMW: totalMW || totalActual,
    renewableSharePct: totalActual > 0 ? Math.round((renewableMW / totalActual) * 100) : 0,
    lowCarbonSharePct: totalActual > 0 ? Math.round((lowCarbonMW / totalActual) * 100) : 0,
    gridLoad,
  };
}

// ─── Installed capacity (static — Elia Annual Report 2024 + ENTSO-E) ─────────
// Source: Elia Power System Overview 2024, CRE/CREG regulated figures
const INSTALLED_CAPACITY_MW: Record<string, number> = {
  "Solar":        8_200,   // MW — Belgium is world's most dense solar per km²
  "Wind Onshore": 3_600,   // MW
  "Wind Offshore":2_300,   // MW (Norther, Rentel, Seastar, Mermaid, Northwester2 etc.)
  "Nuclear":      3_900,   // MW (Doel 1-4, Tihange 1; 2 units phased-out 2022-2023; Doel 4 + Tihange 3 life-extended to 2055)
  "Natural Gas":  5_700,   // MW — CCGT peakers and base load
  "Biofuels":       800,   // MW
  "Hydro":          140,   // MW — small run-of-river + pumped storage (Coo-Trois-Ponts 1,164 MW gross)
  "Storage":        350,   // MW — BESS and other grid-connected storage
};

// ─── Build monthly history (last 12 months) via single GROUP BY API call ─────
async function buildMonthlyHistory(): Promise<any[]> {
  const now = new Date();
  // Go back 12 months from first of current month
  const fromDate = new Date(now.getFullYear(), now.getMonth() - 11, 1);
  const fromStr = `${fromDate.getFullYear()}-${String(fromDate.getMonth() + 1).padStart(2, "0")}-01`;

  const histMap = await fetchAllMonthlyHistory(fromStr);

  // Build ordered month labels (newest at end for chart)
  const results: any[] = [];
  for (let i = 11; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const label = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
    const avgByFuel = histMap.get(label) ?? {};
    const totalAvgMW = Object.values(avgByFuel).reduce((s, v) => s + v, 0);
    const renewableAvgMW = Object.entries(avgByFuel)
      .filter(([f]) => RENEWABLE_FUELS.has(f))
      .reduce((s, [, v]) => s + v, 0);
    const lowCarbonAvgMW = Object.entries(avgByFuel)
      .filter(([f]) => LOW_CARBON_FUELS.has(f))
      .reduce((s, [, v]) => s + v, 0);
    results.push({
      month: label,
      ...avgByFuel,
      totalAvgMW,
      renewableSharePct: totalAvgMW > 0 ? Math.round((renewableAvgMW / totalAvgMW) * 100) : 0,
      lowCarbonSharePct: totalAvgMW > 0 ? Math.round((lowCarbonAvgMW / totalAvgMW) * 100) : 0,
    });
  }
  return results;
}

// ─── Main export ──────────────────────────────────────────────────────────────
export async function getBelgiumData(): Promise<any> {
  const cacheKey = "elia_belgium_full";
  const cached = fromCache(cacheKey, HIST_TTL);
  if (cached) return cached;

  const [liveSnapshot, monthly] = await Promise.all([
    fetchLiveSnapshot().catch(() => null),
    buildMonthlyHistory().catch(() => []),
  ]);

  const result = {
    live: liveSnapshot !== null,
    liveSnapshot,
    monthly,
    installedCapacity: INSTALLED_CAPACITY_MW,
    fetchedAt: new Date().toISOString(),
    apiSource: "Elia opendata.elia.be — 104 public datasets, 15-min resolution",
  };

  toCache(cacheKey, result);
  return result;
}
