import { Bot, AlertTriangle } from "lucide-react";

interface AIContentLabelProps {
  generatedAt?: string;
  model?: string;
  variant?: "banner" | "badge" | "inline";
}

export function AIContentLabel({ generatedAt, model = "GPT-5.1", variant = "banner" }: AIContentLabelProps) {
  const dateStr = generatedAt
    ? new Date(generatedAt).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })
    : null;

  if (variant === "badge") {
    return (
      <span
        data-testid="badge-ai-generated"
        className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300 border border-blue-200 dark:border-blue-800"
      >
        <Bot className="h-3 w-3" />
        AI-Generated
      </span>
    );
  }

  if (variant === "inline") {
    return (
      <span
        data-testid="text-ai-disclosure-inline"
        className="text-xs text-muted-foreground flex items-center gap-1"
      >
        <Bot className="h-3 w-3" />
        AI-generated content — verify independently
      </span>
    );
  }

  return (
    <div
      data-testid="banner-ai-disclosure"
      className="flex items-start gap-3 p-3 rounded-lg bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800 mb-6"
    >
      <AlertTriangle className="h-5 w-5 text-amber-600 dark:text-amber-400 mt-0.5 shrink-0" />
      <div className="text-sm text-amber-800 dark:text-amber-200">
        <span className="font-semibold">AI-Generated Content</span>
        <span className="mx-1">—</span>
        This report was generated by AI ({model})
        {dateStr && <> on {dateStr}</>}.
        All data, figures, and insights should be independently verified before use in decision-making.
      </div>
    </div>
  );
}

export function AIExportDisclosure({ model = "GPT-5.1", generatedAt }: { model?: string; generatedAt?: string }) {
  const dateStr = generatedAt
    ? new Date(generatedAt).toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })
    : "an unspecified date";

  return `⚠ AI-Generated Content — This report was generated by AI (${model}) on ${dateStr}. All data, figures, and insights should be independently verified before use in decision-making.`;
}
